### ISSUE TITLE
Loggly support?

### ISSUE THREAD

**Issue by pankaj22** [reubano/pygogo#11]
Does this library have loggly (https://www.loggly.com/) support ?

**Comment by reubano** [comment]
Based on their [config example](https://github.com/loggly/loggly-python-handler#use-configuration-in-python-file) and the [gogo custom handler example](https://github.com/reubano/pygogo#loggingstreamhandler-instance-in-python), you should be able to do something like this:

```python
from loggly.handlers import HTTPSHandler
import pygogo as gogo

hdlr = HTTPSHandler('https://logs-01.loggly.com/inputs/TOKEN/tag/python')
logger = gogo.Gogo('myLogger', low_hdlr=hdlr).get_logger()
logger.info('Test log')
```

**Comment by reubano** [comment]
I'll assume my previous comment was sufficient. Feel free to reopen if it wasn't.
