### ISSUE TITLE
README.md - misspell

### ISSUE THREAD

**Issue by nicewook** [reubano/pygogo#15]
I think below stdout.log should changed to stdout
Thanks for the package
--------

Disabled dual logging

import pygogo as gogo

logger = gogo.Gogo(monolog=True).logger
logger.debug('debug message')
logger.info('info message')
logger.warning('warning message')
logger.error('error message')
logger.critical('critical message')

# Prints the following to `stdout.log` (all messages at level `INFO` or below):

**Comment by reubano** [comment]
Nice catch! Mind submitting a PR?
