### ISSUE TITLE
csv formatter output invalid

### ISSUE THREAD

**Issue by micimize** [reubano/pygogo#18]
```python
>>> gogo.Gogo(name="root", low_formatter=gogo.formatters.csv_formatter).info('..."hmm"')
# stdout:
# 2019-02-23 10:00:02.825,root.base,INFO,"..."hmm""
```
It should use a [real csv formatter](https://stackoverflow.com/questions/19765139/what-is-the-proper-way-to-do-logging-in-csv-file)

**Comment by reubano** [comment]
Can you please show an example of the expected output?

**Comment by micimize** [comment]
It seems the most standard dublequote-handling csv pattern is quote-escaping (`" -> ""`):
`2019-02-23 10:00:02.825,root.base,INFO,"...""hmm"""`

**Comment by micimize** [comment]
but I think really `csv_formatter` should take `csv.writer` arguments aside from the target, and should init and return a `csv.writer` wrapping formatter similar to the SO answer
