### ISSUE TITLE
Request: Add log rotation for file_hdlr

### ISSUE THREAD

**Issue by AndydeCleyre** [reubano/pygogo#5]
A welcome feature would be built-in log rotation for the file handler, enabled via kwarg for max file size, and maybe another kwarg for the number of old/rotated logs to keep around.

Would you consider that in scope for this project?

**Comment by reubano** [comment]
pygogo is designed to work with the built-in python logging handlers, so you should be able to use the native [RotatingFileHandler](http://docs.python.org/3.5/library/logging.handlers.html#logging.handlers.RotatingFileHandler) without much trouble like in [this example](https://github.com/reubano/pygogo#loggingstreamhandler-instance-in-python). Can you give it a shot and let me know if run into any problems?

**Comment by reubano** [comment]
Closing for now. If my suggestion isn't suitable, feel free to reopen.
