### ISSUE TITLE
ImportError: No module named builtins

### ISSUE THREAD

**Issue by shayanb** [reubano/pygogo#6]
```
Traceback (most recent call last):
  File "testscript.py", line 9, in <module>
    import pygogo as gogo
  File ".../virtualenv/lib/python2.7/site-packages/pygogo/__init__.py", line 52, in <module>
    from builtins import *
ImportError: No module named builtins
```
Say what?

**Comment by glerinsonum** [comment]
![2016-08-19_021539](https://cloud.githubusercontent.com/assets/21057103/17794797/d2713b26-65b2-11e6-9d42-078ca4e119f0.jpg)

**Comment by reubano** [comment]
Let me know if this is still an issue

**Comment by glerinsonum** [comment]
![1](https://cloud.githubusercontent.com/assets/21057103/17831220/1093bcd6-66e3-11e6-9585-2f227350c48d.jpg)
![2](https://cloud.githubusercontent.com/assets/21057103/17831221/109ce4be-66e3-11e6-8b86-c490ea19af23.jpg)
![3](https://cloud.githubusercontent.com/assets/21057103/17831217/107ea35a-66e3-11e6-8841-9c1b4c9e33c9.jpg)
![4](https://cloud.githubusercontent.com/assets/21057103/17831218/1090c788-66e3-11e6-9e8f-a177c7f36d6c.jpg)
![5](https://cloud.githubusercontent.com/assets/21057103/17831219/1091a928-66e3-11e6-80e3-715d5e8ba13f.jpg)


???

**Comment by reubano** [comment]
@glerinsonum I don't see what your posts have to do with this issue (or even this repo). Can you please clarify?

**Comment by glerinsonum** [comment]
![23](https://cloud.githubusercontent.com/assets/21057103/17873397/c2c02b54-68c5-11e6-9f0f-d84baabf54b1.jpg)
![1](https://cloud.githubusercontent.com/assets/21057103/17873395/c2bb4396-68c5-11e6-8b85-9aad69665909.jpg)
![2](https://cloud.githubusercontent.com/assets/21057103/17873396/c2bee168-68c5-11e6-8c60-ea5ed5fda7d5.jpg)
![3](https://cloud.githubusercontent.com/assets/21057103/17873399/c2c41480-68c5-11e6-8c62-e2f541416b4a.jpg)
![4](https://cloud.githubusercontent.com/assets/21057103/17873400/c2c4f56c-68c5-11e6-83e0-1e61b5a45b0b.jpg)
![5](https://cloud.githubusercontent.com/assets/21057103/17873398/c2c3e78a-68c5-11e6-9387-6a8547a12e53.jpg)
![6](https://cloud.githubusercontent.com/assets/21057103/17873401/c2d3cb78-68c5-11e6-919c-9d481f31dda8.jpg)
![7](https://cloud.githubusercontent.com/assets/21057103/17873402/c2d71bd4-68c5-11e6-8418-d7e0659b8a88.jpg)
![8](https://cloud.githubusercontent.com/assets/21057103/17873403/c2d992ba-68c5-11e6-8cd5-a877477dca41.jpg)
![9](https://cloud.githubusercontent.com/assets/21057103/17873406/c2e0885e-68c5-11e6-9d08-bc2fa1059ce4.jpg)
![10](https://cloud.githubusercontent.com/assets/21057103/17873404/c2d9b128-68c5-11e6-9747-648a28912767.jpg)
![11](https://cloud.githubusercontent.com/assets/21057103/17873405/c2debcf4-68c5-11e6-8116-d3a33c1f8b56.jpg)
![12](https://cloud.githubusercontent.com/assets/21057103/17873418/c3e1784e-68c5-11e6-958d-c5199992a419.jpg)
![13](https://cloud.githubusercontent.com/assets/21057103/17873407/c2f28068-68c5-11e6-9bac-b04e8f7fc6a2.jpg)
![14](https://cloud.githubusercontent.com/assets/21057103/17873423/c5ef0c6e-68c5-11e6-813c-6ecdacf06627.jpg)
![15](https://cloud.githubusercontent.com/assets/21057103/17873408/c2f6f40e-68c5-11e6-8562-160142479abb.jpg)
![16](https://cloud.githubusercontent.com/assets/21057103/17873409/c2f724ba-68c5-11e6-9cfd-a0b00a7e4fb4.jpg)
![17](https://cloud.githubusercontent.com/assets/21057103/17873410/c2f8d062-68c5-11e6-96a4-41696f56a368.jpg)
![18](https://cloud.githubusercontent.com/assets/21057103/17873411/c3096972-68c5-11e6-895d-acf894fdc91d.jpg)
![19](https://cloud.githubusercontent.com/assets/21057103/17873412/c30cdb48-68c5-11e6-9f56-f9f42677d0d7.jpg)
![20](https://cloud.githubusercontent.com/assets/21057103/17873413/c315bce0-68c5-11e6-95f3-ca86bb057a30.jpg)
![21](https://cloud.githubusercontent.com/assets/21057103/17873414/c316421e-68c5-11e6-9a7f-5c8767a3547e.jpg)
![22](https://cloud.githubusercontent.com/assets/21057103/17873415/c3225da6-68c5-11e6-9991-a8c2fbaf7104.jpg)

**Comment by glerinsonum** [comment]
### I can't understand why do not there any result, in "log output" as at twitter, for instagram geolocation,

**Comment by glerinsonum** [comment]
![1](https://cloud.githubusercontent.com/assets/21057103/17873666/1fda95c6-68c7-11e6-9f43-38b383a5abad.jpg)
![2](https://cloud.githubusercontent.com/assets/21057103/17873665/1fd9de06-68c7-11e6-9b7c-d601f2862a69.jpg)

**Comment by glerinsonum** [comment]
take a look at those resources of instagram plugin. 


 http://datafilehost.com/d/jNAFNiv8QP

**Comment by glerinsonum** [comment]
take a look at those resources of instagram plugin. 

resources download in this link
 http://datafilehost.com/d/jNAFNiv8QP

**Comment by shayanb** [comment]
@reubano thanks for the quick fix. not sure what is going on with glerinsonum here though.

**Comment by glerinsonum** [comment]
@reubano 

Instagram file,  based python programming for plugin geolocation, not offer result for geolocation.

**Comment by glerinsonum** [comment]
`#!/usr/bin/python
# -*- coding: utf-8 -*-
import os
import logging
import urllib
from urlparse import urlparse, parse_qs
from configobj import ConfigObj

import pytz
from PyQt4.QtGui import QLabel, QLineEdit, QWizard, QWizardPage, QVBoxLayout, QMessageBox, QTextEdit, QPushButton
from instagram.client import InstagramAPI
from models.InputPlugin import InputPlugin
from utilities import GeneralUtilities, QtHandler
import functools
import webbrowser
# set up logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
fh = logging.FileHandler(os.path.join(GeneralUtilities.getLogDir(), 'creepy_main.log'))
fh.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(levelname)s:%(asctime)s  In %(filename)s:%(lineno)d: %(message)s')
fh.setFormatter(formatter)
guiLoggingHandler = QtHandler.QtHandler()
guiLoggingHandler.setFormatter(formatter)
logger.addHandler(fh)
logger.addHandler(guiLoggingHandler)


class Instagram(InputPlugin):
    name = "instagram"
    hasWizard = True
    hasLocationBasedMode = True
    hasRateLimitInfo = True

    def __init__(self):
        # Try and read the labels file
        labels_config = self.getConfigObj(self.name + '.labels')
        try:
            self.labels = labels_config['labels']
        except Exception, err:
            self.labels = None
            logger.error("Could not load the labels file for the  " + self.name + " plugin .")
            logger.error(err)
        self.config, self.options_string = self.readConfiguration("string_options")
        self.api = None
        self.wizard = QWizard()

    def getAuthenticatedAPI(self):
        return InstagramAPI(access_token=self.options_string['hidden_access_token'])

    def isConfigured(self):
        if self.api is None:
            self.api = self.getAuthenticatedAPI()
        try:
            self.api.user()
            return True, ""
        except Exception, err:
            return False, err.error_message

    def searchForTargets(self, search_term):
        logger.debug("Attempting to search for targets. Search term was : " + search_term)
        possibleTargets = []
        try:
            if self.api is None:
                self.api = self.getAuthenticatedAPI()
            results = self.api.user_search(q=search_term)

            for i in results:
                target = {'pluginName': 'Instagram Plugin'}
                target['targetUserid'] = i.id
                target['targetUsername'] = i.username
                target['targetPicture'] = 'profile_pic_%s' % i.id
                target['targetFullname'] = i.full_name
                # save the pic in the temp folder to show it later
                filename = 'profile_pic_%s' % i.id
                temp_file = os.path.join(os.getcwdu(), "temp", filename)
                if not os.path.exists(temp_file):
                    urllib.urlretrieve(i.profile_picture, temp_file)
                possibleTargets.append(target)
            logger.debug(str(len(possibleTargets)) + " possible targets were found matching the search query")
        except Exception, err:
            logger.error("Error searching for targets with instagram plugin.")
            logger.error(err)
        return possibleTargets

    def getAllPhotos(self, uid, count, max_id, photos):
        if self.api is None:
            self.api = self.getAuthenticatedAPI()
        new_photos, next1 = self.api.user_recent_media(user_id=uid, count=count, max_id=max_id)
        if new_photos:
            photos.extend(new_photos)
        if not next1:
            logger.debug("Retrieved {0} photos from instagram.".format(len(photos)))
            return photos
        else:
            a = parse_qs(urlparse(next1).query)
            return self.getAllPhotos(uid, count, a['max_id'][0], photos)

    def searchForResultsNearPlace(self, geocode):
        logger.debug("Attempting to retrieve all photos around {0} from instagram".format(geocode))
        locations_list = []
        try:
            if self.api is None:
                self.api = self.getAuthenticatedAPI()
            if geocode.split(',')[2].endswith('km'):
                distance = int(geocode.split(',')[2].replace('km','')) * 1000
            else:
                distance = int(geocode.split(',')[2].replace('m',''))
            # Set defaults
            if distance == 0 or distance > 5000:
                distance = 1000

            photos_list = self.api.media_search(q="*", distance=geocode.split(',')[2], count=200, lat=geocode.split(',')[0], lng=geocode.split(',')[1])
            for i in photos_list:
                if hasattr(i, 'location'):
                    loc = {}
                    loc['plugin'] = "instagram"
                    loc['username'] = i.user.username
                    loc['context'] = i.caption.text if i.caption else unicode('No Caption', 'utf-8')
                    loc['infowindow'] = self.constructContextInfoWindow(i, i.user.username)
                    loc['date'] = pytz.utc.localize(i.created_time)
                    loc['lat'] = i.location.point.latitude
                    loc['lon'] = i.location.point.longitude
                    loc['media_url'] = i.get_low_resolution_url()
                    loc['shortName'] = i.location.name
                    if len(str(loc['lat'])) < 4 and len(str(loc['lon'])) < 4:
                        loc['accuracy'] = 'low'
                    else:
                        loc['accuracy'] = 'high'
                    locations_list.append(loc)
            logger.debug(str(len(locations_list)) + " photos have been retrieved")
        except Exception, err:
            logger.error(err)
            logger.error("Error getting locations from instagram plugin")
        return locations_list

    def returnAnalysis(self, target, search_params):
        logger.debug("Attempting to retrieve all photos for user " + target['targetUsername'])
        locations_list = []
        try:
            if self.api is None:
                self.api = self.getAuthenticatedAPI()
            photos_list = self.getAllPhotos(target['targetUserid'], 200, None, [])
            for i in photos_list:
                if hasattr(i, 'location'):
                    loc = {}
                    loc['plugin'] = "instagram"
                    loc['username'] = i.user.username
                    loc['context'] = i.caption.text if i.caption else unicode('No Caption', 'utf-8')
                    loc['infowindow'] = self.constructContextInfoWindow(i, target['targetUsername'])
                    loc['date'] = pytz.utc.localize(i.created_time)
                    loc['lat'] = i.location.point.latitude
                    loc['lon'] = i.location.point.longitude
                    loc['media_url'] = i.get_low_resolution_url()
                    loc['shortName'] = i.location.name
                    if len(str(loc['lat'])) < 4 and len(str(loc['lon']).len) < 4:
                        loc['accuracy'] = 'low'
                    else:
                        loc['accuracy'] = 'high'
                    loc['accuracy'] = 'high'
                    locations_list.append(loc)
            logger.debug("{0} locations have been retrieved".format(len(locations_list)))
        except Exception, err:
            logger.error(err)
            logger.error("Error getting locations from instagram plugin")
        return locations_list, None

    def openLinkInBrowser(self, link):
        webbrowser.open(link, new=1)

    def runConfigWizard(self):
        try:
            api = InstagramAPI(client_id=self.options_string['hidden_client_id'],
                               client_secret=self.options_string['hidden_client_secret'],
                               redirect_uri=self.options_string['redirect_uri'])
            url = api.get_authorize_login_url()

            self.wizard.setWindowTitle("Instagram plugin configuration wizard")
            page1 = QWizardPage()
            layout1 = QVBoxLayout()
            txtArea = QLabel()
            txtArea.setText("Please copy the following link to your browser window. \n " +
                                  "Once you authenticate with Instagram you will be redirected to www.geocreepy.com and get your token. Copy the token to the input field below:")
            urlArea = QLineEdit()
            urlArea.setObjectName('urlArea')
            urlArea.setText(url)
            inputLink = QLineEdit()
            inputLink.setObjectName("inputLink")
            labelLink = QLabel("Your token value:")
            openInBrowserButton = QPushButton("Open in browser")
            openInBrowserButton.clicked.connect(functools.partial(self.openLinkInBrowser, url))
            layout1.addWidget(txtArea)
            layout1.addWidget(urlArea)
            layout1.addWidget(openInBrowserButton)
            layout1.addWidget(labelLink)
            layout1.addWidget(inputLink)
            page1.setLayout(layout1)
            self.wizard.addPage(page1)
            self.wizard.resize(600, 400)
            if self.wizard.exec_():
                c = str(inputLink.text())
                if c:
                    try:
                        access_token = api.exchange_code_for_access_token(code=c)
                        self.options_string['hidden_access_token'] = access_token[0]
                        self.config.write()
                    except Exception, err:
                        self.showWarning("Error Getting Access Token",
                                         "Please verify that the link you pasted was correct. Try running the wizard again.")
                else:
                    self.showWarning("Error Getting Access Token",
                                     "Please verify that the link you pasted was correct. Try running the wizard again.")

        except Exception, err:
            logger.error(err)
            self.showWarning("Error", "Error was {0}".format(err))

    def parseRedirectUrl(self, link):
        try:
            return parse_qs(urlparse(link).query)['code'][0]
        except Exception, err:
            logger.error(err)
            return None

    def showWarning(self, title, text):
        QMessageBox.warning(self.wizard, title, text)

    def constructContextInfoWindow(self, photo, username):
        html = unicode(self.options_string['infowindow_html'], 'utf-8')
        caption = photo.caption.text if photo.caption else unicode('No Caption', 'utf-8')
        return html.replace("@TEXT@", caption).replace("@DATE@", pytz.utc.localize(photo.created_time).strftime(
            "%Y-%m-%d %H:%M:%S %z")).replace("@PLUGIN@", u"instagram").replace("@LINK@", photo.link).replace("@MEDIA_URL@", photo.get_low_resolution_url()).replace("@USERNAME@", username)

    def getLabelForKey(self, key):
        '''
        read the plugin_name.labels 
        file and try to get label text for the key that was asked
        '''
        if not self.labels:
            return key
        if key not in self.labels.keys():
            return key
        return self.labels[key]
`

**Comment by glerinsonum** [comment]
#!/usr/bin/python
# -*- coding: utf-8 -*-
import os
import logging
import urllib
from urlparse import urlparse, parse_qs
from configobj import ConfigObj

import pytz
from PyQt4.QtGui import QLabel, QLineEdit, QWizard, QWizardPage, QVBoxLayout, QMessageBox, QTextEdit, QPushButton
from instagram.client import InstagramAPI
from models.InputPlugin import InputPlugin
from utilities import GeneralUtilities, QtHandler
import functools
import webbrowser
# set up logging
logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)
fh = logging.FileHandler(os.path.join(GeneralUtilities.getLogDir(), 'creepy_main.log'))
fh.setLevel(logging.DEBUG)
formatter = logging.Formatter('%(levelname)s:%(asctime)s  In %(filename)s:%(lineno)d: %(message)s')
fh.setFormatter(formatter)
guiLoggingHandler = QtHandler.QtHandler()
guiLoggingHandler.setFormatter(formatter)
logger.addHandler(fh)
logger.addHandler(guiLoggingHandler)


class Instagram(InputPlugin):
    name = "instagram"
    hasWizard = True
    hasLocationBasedMode = True
    hasRateLimitInfo = True

    def __init__(self):
        # Try and read the labels file
        labels_config = self.getConfigObj(self.name + '.labels')
        try:
            self.labels = labels_config['labels']
        except Exception, err:
            self.labels = None
            logger.error("Could not load the labels file for the  " + self.name + " plugin .")
            logger.error(err)
        self.config, self.options_string = self.readConfiguration("string_options")
        self.api = None
        self.wizard = QWizard()

    def getAuthenticatedAPI(self):
        return InstagramAPI(access_token=self.options_string['hidden_access_token'])

    def isConfigured(self):
        if self.api is None:
            self.api = self.getAuthenticatedAPI()
        try:
            self.api.user()
            return True, ""
        except Exception, err:
            return False, err.error_message

    def searchForTargets(self, search_term):
        logger.debug("Attempting to search for targets. Search term was : " + search_term)
        possibleTargets = []
        try:
            if self.api is None:
                self.api = self.getAuthenticatedAPI()
            results = self.api.user_search(q=search_term)

            for i in results:
                target = {'pluginName': 'Instagram Plugin'}
                target['targetUserid'] = i.id
                target['targetUsername'] = i.username
                target['targetPicture'] = 'profile_pic_%s' % i.id
                target['targetFullname'] = i.full_name
                # save the pic in the temp folder to show it later
                filename = 'profile_pic_%s' % i.id
                temp_file = os.path.join(os.getcwdu(), "temp", filename)
                if not os.path.exists(temp_file):
                    urllib.urlretrieve(i.profile_picture, temp_file)
                possibleTargets.append(target)
            logger.debug(str(len(possibleTargets)) + " possible targets were found matching the search query")
        except Exception, err:
            logger.error("Error searching for targets with instagram plugin.")
            logger.error(err)
        return possibleTargets

    def getAllPhotos(self, uid, count, max_id, photos):
        if self.api is None:
            self.api = self.getAuthenticatedAPI()
        new_photos, next1 = self.api.user_recent_media(user_id=uid, count=count, max_id=max_id)
        if new_photos:
            photos.extend(new_photos)
        if not next1:
            logger.debug("Retrieved {0} photos from instagram.".format(len(photos)))
            return photos
        else:
            a = parse_qs(urlparse(next1).query)
            return self.getAllPhotos(uid, count, a['max_id'][0], photos)

    def searchForResultsNearPlace(self, geocode):
        logger.debug("Attempting to retrieve all photos around {0} from instagram".format(geocode))
        locations_list = []
        try:
            if self.api is None:
                self.api = self.getAuthenticatedAPI()
            if geocode.split(',')[2].endswith('km'):
                distance = int(geocode.split(',')[2].replace('km','')) * 1000
            else:
                distance = int(geocode.split(',')[2].replace('m',''))
            # Set defaults
            if distance == 0 or distance > 5000:
                distance = 1000

            photos_list = self.api.media_search(q="*", distance=geocode.split(',')[2], count=200, lat=geocode.split(',')[0], lng=geocode.split(',')[1])
            for i in photos_list:
                if hasattr(i, 'location'):
                    loc = {}
                    loc['plugin'] = "instagram"
                    loc['username'] = i.user.username
                    loc['context'] = i.caption.text if i.caption else unicode('No Caption', 'utf-8')
                    loc['infowindow'] = self.constructContextInfoWindow(i, i.user.username)
                    loc['date'] = pytz.utc.localize(i.created_time)
                    loc['lat'] = i.location.point.latitude
                    loc['lon'] = i.location.point.longitude
                    loc['media_url'] = i.get_low_resolution_url()
                    loc['shortName'] = i.location.name
                    if len(str(loc['lat'])) < 4 and len(str(loc['lon'])) < 4:
                        loc['accuracy'] = 'low'
                    else:
                        loc['accuracy'] = 'high'
                    locations_list.append(loc)
            logger.debug(str(len(locations_list)) + " photos have been retrieved")
        except Exception, err:
            logger.error(err)
            logger.error("Error getting locations from instagram plugin")
        return locations_list

    def returnAnalysis(self, target, search_params):
        logger.debug("Attempting to retrieve all photos for user " + target['targetUsername'])
        locations_list = []
        try:
            if self.api is None:
                self.api = self.getAuthenticatedAPI()
            photos_list = self.getAllPhotos(target['targetUserid'], 200, None, [])
            for i in photos_list:
                if hasattr(i, 'location'):
                    loc = {}
                    loc['plugin'] = "instagram"
                    loc['username'] = i.user.username
                    loc['context'] = i.caption.text if i.caption else unicode('No Caption', 'utf-8')
                    loc['infowindow'] = self.constructContextInfoWindow(i, target['targetUsername'])
                    loc['date'] = pytz.utc.localize(i.created_time)
                    loc['lat'] = i.location.point.latitude
                    loc['lon'] = i.location.point.longitude
                    loc['media_url'] = i.get_low_resolution_url()
                    loc['shortName'] = i.location.name
                    if len(str(loc['lat'])) < 4 and len(str(loc['lon']).len) < 4:
                        loc['accuracy'] = 'low'
                    else:
                        loc['accuracy'] = 'high'
                    loc['accuracy'] = 'high'
                    locations_list.append(loc)
            logger.debug("{0} locations have been retrieved".format(len(locations_list)))
        except Exception, err:
            logger.error(err)
            logger.error("Error getting locations from instagram plugin")
        return locations_list, None

    def openLinkInBrowser(self, link):
        webbrowser.open(link, new=1)

    def runConfigWizard(self):
        try:
            api = InstagramAPI(client_id=self.options_string['hidden_client_id'],
                               client_secret=self.options_string['hidden_client_secret'],
                               redirect_uri=self.options_string['redirect_uri'])
            url = api.get_authorize_login_url()

            self.wizard.setWindowTitle("Instagram plugin configuration wizard")
            page1 = QWizardPage()
            layout1 = QVBoxLayout()
            txtArea = QLabel()
            txtArea.setText("Please copy the following link to your browser window. \n " +
                                  "Once you authenticate with Instagram you will be redirected to www.geocreepy.com and get your token. Copy the token to the input field below:")
            urlArea = QLineEdit()
            urlArea.setObjectName('urlArea')
            urlArea.setText(url)
            inputLink = QLineEdit()
            inputLink.setObjectName("inputLink")
            labelLink = QLabel("Your token value:")
            openInBrowserButton = QPushButton("Open in browser")
            openInBrowserButton.clicked.connect(functools.partial(self.openLinkInBrowser, url))
            layout1.addWidget(txtArea)
            layout1.addWidget(urlArea)
            layout1.addWidget(openInBrowserButton)
            layout1.addWidget(labelLink)
            layout1.addWidget(inputLink)
            page1.setLayout(layout1)
            self.wizard.addPage(page1)
            self.wizard.resize(600, 400)
            if self.wizard.exec_():
                c = str(inputLink.text())
                if c:
                    try:
                        access_token = api.exchange_code_for_access_token(code=c)
                        self.options_string['hidden_access_token'] = access_token[0]
                        self.config.write()
                    except Exception, err:
                        self.showWarning("Error Getting Access Token",
                                         "Please verify that the link you pasted was correct. Try running the wizard again.")
                else:
                    self.showWarning("Error Getting Access Token",
                                     "Please verify that the link you pasted was correct. Try running the wizard again.")

        except Exception, err:
            logger.error(err)
            self.showWarning("Error", "Error was {0}".format(err))

    def parseRedirectUrl(self, link):
        try:
            return parse_qs(urlparse(link).query)['code'][0]
        except Exception, err:
            logger.error(err)
            return None

    def showWarning(self, title, text):
        QMessageBox.warning(self.wizard, title, text)

    def constructContextInfoWindow(self, photo, username):
        html = unicode(self.options_string['infowindow_html'], 'utf-8')
        caption = photo.caption.text if photo.caption else unicode('No Caption', 'utf-8')
        return html.replace("@TEXT@", caption).replace("@DATE@", pytz.utc.localize(photo.created_time).strftime(
            "%Y-%m-%d %H:%M:%S %z")).replace("@PLUGIN@", u"instagram").replace("@LINK@", photo.link).replace("@MEDIA_URL@", photo.get_low_resolution_url()).replace("@USERNAME@", username)

    def getLabelForKey(self, key):
        '''
        read the plugin_name.labels 
        file and try to get label text for the key that was asked
        '''
        if not self.labels:
            return key
        if key not in self.labels.keys():
            return key
        return self.labels[key]

**Comment by glerinsonum** [comment]
![2016-08-23_151057](https://cloud.githubusercontent.com/assets/21057103/17892926/e408473c-6943-11e6-9a05-889133e706ee.png)

### This is an software based python-GUI, but not offer any result for geolocation

**Comment by reubano** [comment]
@glerinsonum if you have a problem with [creepy](https://github.com/jkakavas/creepy) please file an issue [there](https://github.com/jkakavas/creepy/issues). As you have shown in the screenshot, pygogo's logging functionality is working.
